### ISSUE TITLE
Deprecated selector in `boot-java/styles/hints.atom-text-editor.less`

### ISSUE THREAD

**Issue by ciazhar** [spring-projects/atom-boot-java#1]
In `boot-java/styles/hints.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter-boot-hint:before` => `atom-text-editor.editor .gutter-boot-hint:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by BoykoAlex** [comment]
Aha, thanks for pointing this out. I'll correct it.

**Comment by BoykoAlex** [comment]
Corrected with this commit https://github.com/spring-projects/sts4/commit/28f36ae9b7faeb61cf648b598fe0b680963e055b
